config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'logbooks#index'
  get 'users/:user_id/areas/:area_id/index', to: 'users#index'
  resources :users, only: [:edit, :update, :show] do
    collection do
      get 'search'
    end
  end
  resources :areas, only: [:new, :create, :destroy] do
    resources :conditions, only: [:new, :create]
    resources :items,      only: [:new, :create]
    resources :logbooks,   only: [:index, :new, :create]
  end
  resources :tweets, only:[:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :user
  has_one    :condition, dependent: :destroy
  has_one    :item, dependent: :destroy
  has_one    :logbook, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :entry

  with_options presence: true do
    validates :dive_day, format: { with: /\A\d{4}-\d{2}-\d{2}\z/ }
    validates :region
  end
  with_options numericality: { other_than: 1 } do
    validates :entry_id
  end

  def self.search(search, num)
    if search != ''
      if num == 1
        Area.where('dive_day LIKE(?)', "#{search}-__")
      elsif num == 2
        Area.where('dive_day LIKE(?)', "20__-#{search}-__")
      elsif num == 3
        Area.where('dive_day LIKE(?)', "#{search}%")
      end
    else
      Area.all
    end
  end
end

app/models/capacity.rb
class Capacity < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '8' },
    { id: 3, name: '10' },
    { id: 4, name: '12' },
    { id: 5, name: '14' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :area
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :tide

  validates :weather, presence: true
  validates :wave, presence: true, numericality: true, format: { with: /\A-?[0-9]+(\.[0-9]+)?\z/ }

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :wind
    validates :temperature
    validates :water_temperature
  end
  with_options numericality: { other_than: 1 } do
    validates :tide_id
  end
end

app/models/entry.rb
class Entry < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ボートダイブ' },
    { id: 3, name: 'ビーチダイブ' },
    { id: 4, name: 'ドリフトダイブ' },
    { id: 5, name: 'ナイトダイブ' }
  ]

  include ActiveHash::Associations
  has_many :areas
end

app/models/equipment.rb
class Equipment < ApplicationRecord

  belongs_to :area

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :capacity
  belongs_to :type
  belongs_to :suitstype

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :area, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :capacity
  belongs_to :type
  belongs_to :suitstype

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :thickness
    validates :weight
  end
  with_options numericality: { other_than: 1 } do
    validates :suitstype_id
    validates :capacity_id
    validates :type_id
  end
end

app/models/logbook.rb
class Logbook < ApplicationRecord
  belongs_to :area, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :entry_time
    validates :exit_time
  end
  with_options presence: true do
    validates :text
    validates :point
  end

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :start_air
    validates :finish_air
    validates :max_depth
    validates :ave_depth
    validates :count
  end

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/month.rb
class Month < ActiveHash::Base
  self.data = [
    { id: 1, name: '' },
    { id: 2, name: '01' },
    { id: 3, name: '02' },
    { id: 4, name: '03' },
    { id: 5, name: '04' },
    { id: 6, name: '05' },
    { id: 7, name: '06' },
    { id: 8, name: '07' },
    { id: 9, name: '08' },
    { id: 10, name: '09' },
    { id: 11, name: '10' },
    { id: 12, name: '11' },
    { id: 13, name: '12' }
  ]

  include ActiveHash::Associations
  has_many :area
end

app/models/suitstype.rb
class Suitstype < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ウェットスーツ' },
    { id: 3, name: 'ドライスーツ' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/tide.rb
class Tide < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'なし' },
    { id: 3, name: 'とても弱い' },
    { id: 4, name: '弱い' },
    { id: 5, name: '強い' },
    { id: 6, name: 'とても強い' }
  ]

  include ActiveHash::Associations
  has_many :conditions
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :text, presence: true
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'アルミ' },
    { id: 3, name: 'スチール' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :areas, dependent: :destroy
  has_many :tweets
end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [
    { id: 1, name: '' },
    { id: 2, name: '2020' },
    { id: 3, name: '2021' },
    { id: 4, name: '2022' },
    { id: 5, name: '2023' },
    { id: 6, name: '2024' },
    { id: 7, name: '2025' },
    { id: 8, name: '2026' },
    { id: 9, name: '2027' },
    { id: 10, name: '2028' },
    { id: 11, name: '2029' },
    { id: 12, name: '2030' },
    { id: 13, name: '2031' },
    { id: 14, name: '2032' },
    { id: 15, name: '2033' },
    { id: 16, name: '2034' },
    { id: 17, name: '2035' },
    { id: 18, name: '2036' },
    { id: 19, name: '2037' },
    { id: 20, name: '2038' },
    { id: 21, name: '2039' },
    { id: 22, name: '2040' },
    { id: 23, name: '2041' },
    { id: 24, name: '2042' },
    { id: 25, name: '2043' },
    { id: 26, name: '2044' },
    { id: 27, name: '2045' },
    { id: 28, name: '2046' },
    { id: 29, name: '2047' },
    { id: 30, name: '2048' },
    { id: 31, name: '2049' },
    { id: 32, name: '2050' }
  ]

  include ActiveHash::Associations
  has_many :area
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @all = Area.find(params[:area_id])
    @areas = @user.areas
  end

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @areas = user.areas
  end

  def search
    if params[:year].present? && params[:month].present?
      keyword = "#{params[:year]}-#{params[:month]}"
      @areas = Area.search(keyword, 1)
    elsif params[:year] == ''
      keyword = params[:month].to_s
      @areas = Area.search(keyword, 2)
    else
      keyword = params[:year].to_s
      @areas = Area.search(keyword, 3)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logbooks_helper.rb
module LogbooksHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= render "shared/mypage" %>
<main>
  <div class="new-edit-btn-my">
    <%= link_to "ツイート確認", tweets_path, class:"head-text" %>
    <%= link_to "ログブック", user_path(current_user.id), class:"head-text" %>
    <%= link_to "トップページ", root_path, class:"head-text" %>
  </div>
<div class="main">
  <div class="logbook-center">
    <div class="day-list">
      <% @areas.each do |area| %>
        <% if "#{area.id}" == "#{params[:area_id]}" %>
        <div class="day-point">
          <%= link_to "/users/#{area.user_id}/areas/#{area.id}/index", class: "btn-show" do %>
            <p><%= area.dive_day %></p>
            <p><%= area.region%></p>
          <% end %>
        </div>
        <% else %>
        <div class="day-point">
          <%= link_to "/users/#{area.user_id}/areas/#{area.id}/index", class: "btn-flat-border" do %>
            <p><%= area.dive_day %></p>
            <p><%= area.region%></p>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <% if @all.present? %>
    <div class="logbook-list">
      <div class="top-log">
        <ul class="condition-log">
          <h3 class="logbook-sub-title">コンディション</h3>
          <% if @all.condition.present? %>
            <div class="lists-log">
              <p class="log-span">天気</p><%= @all.condition.weather %>
            </div>
            <div class="lists-log">
              <p class="log-span">風速</p><%= @all.condition.wind %>/m
            </div>
            <div class="lists-log">
              <p class="log-span">気温</p><%= @all.condition.temperature %>/℃
            </div>
            <div class="lists-log">
              <p class="log-span">水温</p><%= @all.condition.water_temperature %>/℃
            </div>
            <div class="lists-log">
              <p class="log-span">波高</p><%= @all.condition.wave %>/m
            </div>
            <div class="lists-log">
              <p class="log-span">潮流</p><%= @all.condition.tide.name %>
            </div>
            <ul class="item-log">
          <% else %>
            <Ul>
            <div> No data </div>
            </ul>
          <% end %>
          <h3 class="logbook-sub-title">装備品</h3>
          <% if @all.item.present? %>
          <div class="lists-log">
            <p class="log-span">スーツ</p><%= @all.item.suitstype.name %>
          </div>
          <div class="lists-log">
            <p class="log-span">厚み</p><%= @all.item.thickness %>/mm
          </div>
          <div class="lists-log">
            <p class="log-span">ウエイト</p><%= @all.item.weight %>/kg
          </div>
          <div class="lists-log">
            <p class="log-span">タンクタイプ</p><%= @all.item.type.name %>
          </div>
          <div class="lists-log">
            <p class="log-span">タンク容量</p><%= @all.item.capacity.name %>/L
          </div>
          <% if @all.logbook.image.attached? %>
          <p>Photo</p>
          <%= image_tag @all.logbook.image.variant(resize: '500x500'), class: 'logbook-image' %>
          <% end %><%# else 後でダミー画像おく %>
          </ul>
          <% else %>
          <Ul>
          <div> No data </div>
          </ul>
          <% end %>
        </ul>
        <div class="image-area">
        <% if @all.logbook.present? %>
      </div>
        <ul class="logbook-log">
          <h3 class="logbook-sub-title">記録</h3>
          <div class="lists-log">
            <p class="log-span">本数</p><%= @all.logbook.count %>/本目
          </div>
          <div class="lists-log">
            <p class="log-span">エントリー方法</p><%= @all.entry.name %>
          </div>
          <div class="lists-log">
            <p class="log-span">ポイント</p><%= @all.logbook.point %>
          </div>
          <div class="lists-log">
            <p class="log-span">エントリータイム</p><%= @all.logbook.entry_time.strftime('%H:%M') %>
          </div>
          <div class="lists-log">
            <p class="log-span">エキジットタイム</p><%= @all.logbook.exit_time.strftime('%H:%M') %>
          </div>          
          <div class="lists-log">
            <p class="log-span">スタート（残圧）</p><%= @all.logbook.start_air %>/bar
          </div>
          <div class="lists-log">
            <p class="log-span">エキジット（残圧）</p><%= @all.logbook.finish_air %>/bar
          </div>
          <div class="lists-log">
            <p class="log-span">最大深度</p><%= @all.logbook.max_depth %>/m
          </div>
          <div class="lists-log">
            <p class="log-span">平均深度</p><%= @all.logbook.ave_depth %>/m
          </div>
          <div class="logbook-log-text">
            <p class="border">備考（一緒に潜ったバディ・発見した水中生物など）</p>
            <%= @all.logbook.text %>
          </div>
          <div class="delete-btn">
            <%= link_to 'ログの削除', area_path(params[:area_id]), method: :delete, class: "tweets-nickname" %>
          </div>
        </ul>
        <% else %>
          <Ul>
          <p>記録</p>
          <div> No data </div>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
  <% else %>
  <p> no data </p>
  <% end %>
</div>
</main>

app/views/users/search.html.erb
<%= render "shared/mypage" %>
<main>
  <div class="main">
    <div class="logbook-center">
      <div class="day-list">
      <% @areas.each do |area| %>
        <div class="day-point">
          <%= link_to "/users/#{area.user_id}/areas/#{area.id}/index", class: "btn-flat-border" do %>
            <p><%= area.dive_day %></p>
            <p><%= area.region%></p>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<%= render "shared/mypage" %>
<main>
  <div class="new-edit-btn-my">
    <%= link_to "ツイート確認", tweets_path, class:"head-text" %>
    <%= link_to "ログブック", user_path(current_user.id), class:"head-text" %>
    <%= link_to "トップページ", root_path, class:"head-text" %>
  </div>
<div class="main">
  <div class="logbook-center">
    <div class="day-list">
    <% @areas.each do |area| %>
      <div class="day-point">
        <%= link_to "/users/#{area.user_id}/areas/#{area.id}/index", class: "btn-flat-border" do %>
          <p><%= area.dive_day %></p>
          <p><%= area.region%></p>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>
</main>