config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'logbooks#index'
  get 'users/:user_id/areas/:area_id/index', to: 'users#index'
  resources :users, only: [:edit, :update, :show] do
    collection do
      get 'search'
    end
  end
  resources :areas, only: [:new, :create, :destroy] do
    resources :conditions, only: [:new, :create]
    resources :items,      only: [:new, :create]
    resources :logbooks,   only: [:index, :new, :create]
  end
  resources :tweets, only:[:index, :new, :create, :edit, :update, :destroy]
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :user
  has_one    :condition, dependent: :destroy
  has_one    :item, dependent: :destroy
  has_one    :logbook, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :entry

  with_options presence: true do
    validates :dive_day, format: { with: /\A\d{4}-\d{2}-\d{2}\z/ }
    validates :region
  end
  with_options numericality: { other_than: 1 } do
    validates :entry_id
  end

  def self.search(search, num)
    if search != ''
      if num == 1
        Area.where('dive_day LIKE(?)', "#{search}-__")
      elsif num == 2
        Area.where('dive_day LIKE(?)', "20__-#{search}-__")
      elsif num == 3
        Area.where('dive_day LIKE(?)', "#{search}%")
      end
    else
      Area.all
    end
  end
end

app/models/capacity.rb
class Capacity < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '8' },
    { id: 3, name: '10' },
    { id: 4, name: '12' },
    { id: 5, name: '14' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :area
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :tide

  validates :weather, presence: true
  validates :wave, presence: true, numericality: true, format: { with: /\A-?[0-9]+(\.[0-9]+)?\z/ }

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :wind
    validates :temperature
    validates :water_temperature
  end
  with_options numericality: { other_than: 1 } do
    validates :tide_id
  end
end

app/models/entry.rb
class Entry < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ボートダイブ' },
    { id: 3, name: 'ビーチダイブ' },
    { id: 4, name: 'ドリフトダイブ' },
    { id: 5, name: 'ナイトダイブ' }
  ]

  include ActiveHash::Associations
  has_many :areas
end

app/models/equipment.rb
class Equipment < ApplicationRecord

  belongs_to :area

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :capacity
  belongs_to :type
  belongs_to :suitstype

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :area, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :capacity
  belongs_to :type
  belongs_to :suitstype

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :thickness
    validates :weight
  end
  with_options numericality: { other_than: 1 } do
    validates :suitstype_id
    validates :capacity_id
    validates :type_id
  end
end

app/models/logbook.rb
class Logbook < ApplicationRecord
  belongs_to :area, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :entry_time
    validates :exit_time
  end
  with_options presence: true do
    validates :text
    validates :point
  end

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :start_air
    validates :finish_air
    validates :max_depth
    validates :ave_depth
    validates :count
  end

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/month.rb
class Month < ActiveHash::Base
  self.data = [
    { id: 1, name: '' },
    { id: 2, name: '01' },
    { id: 3, name: '02' },
    { id: 4, name: '03' },
    { id: 5, name: '04' },
    { id: 6, name: '05' },
    { id: 7, name: '06' },
    { id: 8, name: '07' },
    { id: 9, name: '08' },
    { id: 10, name: '09' },
    { id: 11, name: '10' },
    { id: 12, name: '11' },
    { id: 13, name: '12' }
  ]

  include ActiveHash::Associations
  has_many :area
end

app/models/suitstype.rb
class Suitstype < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ウェットスーツ' },
    { id: 3, name: 'ドライスーツ' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/tide.rb
class Tide < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'なし' },
    { id: 3, name: 'とても弱い' },
    { id: 4, name: '弱い' },
    { id: 5, name: '強い' },
    { id: 6, name: 'とても強い' }
  ]

  include ActiveHash::Associations
  has_many :conditions
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :text, presence: true
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'アルミ' },
    { id: 3, name: 'スチール' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :areas, dependent: :destroy
  has_many :tweets
end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [
    { id: 1, name: '' },
    { id: 2, name: '2020' },
    { id: 3, name: '2021' },
    { id: 4, name: '2022' },
    { id: 5, name: '2023' },
    { id: 6, name: '2024' },
    { id: 7, name: '2025' },
    { id: 8, name: '2026' },
    { id: 9, name: '2027' },
    { id: 10, name: '2028' },
    { id: 11, name: '2029' },
    { id: 12, name: '2030' },
    { id: 13, name: '2031' },
    { id: 14, name: '2032' },
    { id: 15, name: '2033' },
    { id: 16, name: '2034' },
    { id: 17, name: '2035' },
    { id: 18, name: '2036' },
    { id: 19, name: '2037' },
    { id: 20, name: '2038' },
    { id: 21, name: '2039' },
    { id: 22, name: '2040' },
    { id: 23, name: '2041' },
    { id: 24, name: '2042' },
    { id: 25, name: '2043' },
    { id: 26, name: '2044' },
    { id: 27, name: '2045' },
    { id: 28, name: '2046' },
    { id: 29, name: '2047' },
    { id: 30, name: '2048' },
    { id: 31, name: '2049' },
    { id: 32, name: '2050' }
  ]

  include ActiveHash::Associations
  has_many :area
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logbooks_helper.rb
module LogbooksHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogbookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="foot-wrap">
    <div class="menu-left">
      <h3><%= link_to image_tag("white-logo.png", class:"footer-log-icon"), "/" %></h3>
        <div class="footer-text">
          <p>ダイビングのログをパソコンやスマホで記録するものです。</p>
          <p>ツイート機能をつけることで友人と共有をできるようにしました。</p>
        </div>
      </div>
      <small class="cmark">©️copyright LOGDIVERS 2020
    </small>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="my-page-header">
  <div class="top-page-contents">
    <div class="left-contents">
      <div class="top-icon">
        <%= link_to image_tag("white-logo.png", class:"log-icon"), "/" %>
      </div>
    </div>
    <div class="right">
      <div class="right-contents">
        <% if user_signed_in? %>
          <%= render "shared/search" %>
          <ul class="lists-right">
            <li class="icon-area"><%= link_to image_tag("home-icon.png", class:"right-icon"), tweets_path %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_mypage.html.erb
<header class="my-header">
  <div class="top-page-contents">
    <div class="left-contents">
      <div class="top-icon">
        <%= link_to image_tag("toplogo.png", class:"log-icon"), "/" %>
        <%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %>
        さんのマイページ
      </div>
    </div>
    <div class="right">
      <div class="right-contents">
          <%= render "shared/search" %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_search.html.erb
        <div class="search" style="text-align: right">
        <%= form_with(url: search_users_path, local: true, method: :get) do |form| %>
          日付検索：<%= form.collection_select(:year, Year.all, :name, :name ) %>
          <%= form.collection_select(:month, Month.all, :name, :name ) %>
          <%= form.submit "検索" %>
        <% end %>
        </div>

app/views/shared/_second-header.html.erb
<header class="top-page-header">
<div class="top-page-contents">
  <div class="left-contents">
    <div class="top-icon">
      <%= link_to image_tag("toplogo.png", class:"log-icon"), "/" %>
      <% if user_signed_in? %>
        <%= link_to current_user.nickname, root_path, class: "user-nickname" %>
      <% end %>
    </div>
  </div>
        <div class="second-right">
      <div class="right-contents">
          <ul class="lists-right">
            <li class="icon-area"><%= link_to image_tag("home-icon.png", class:"right-icon"), user_path(current_user.id) %></li>
          </ul>
      </div>
    </div>
  </div>
</div>
</header>

app/views/shared/_tweet.html.erb
<ul class="tweet-contents">
  <li class="tweet-list">
  <% if @tweets.present? %>
    <% @tweets.each do |tweet| %>
    <div class="group">
      <div class="tweet-image-area">
          <%= image_tag tweet.image.variant(resize: '600x400'), class: 'tweet-image' if tweet.image.attached? %>
      </div>
      <div class="tweets-nickname-area">
        <h3 class="tweets-nickname">
          投稿日：<%= l tweet.user.created_at %>
        </h3>
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%= link_to '編集', edit_tweet_path(tweet.id), class: "tweets-nickname" %>
          <%= link_to '削除', tweet_path(tweet.id), method: :delete, class: "tweets-nickname" %>
        <% end %>
        <div class="tweet-text">
          <%= tweet.text %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  </li>
</ul>