config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'logbooks#index'
  get 'users/:user_id/areas/:area_id/index', to: 'users#index'
  resources :users, only: [:edit, :update, :show] do
    collection do
      get 'search'
    end
  end
  resources :areas, only: [:new, :create, :destroy] do
    resources :conditions, only: [:new, :create]
    resources :items,      only: [:new, :create]
    resources :logbooks,   only: [:index, :new, :create]
  end
  resources :tweets, only:[:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :user
  has_one    :condition, dependent: :destroy
  has_one    :item, dependent: :destroy
  has_one    :logbook, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :entry

  with_options presence: true do
    validates :dive_day, format: { with: /\A\d{4}-\d{2}-\d{2}\z/ }
    validates :region
  end
  with_options numericality: { other_than: 1 } do
    validates :entry_id
  end

  def self.search(search, num)
    if search != ''
      if num == 1
        Area.where('dive_day LIKE(?)', "#{search}-__")
      elsif num == 2
        Area.where('dive_day LIKE(?)', "20__-#{search}-__")
      elsif num == 3
        Area.where('dive_day LIKE(?)', "#{search}%")
      end
    else
      Area.all
    end
  end
end

app/models/capacity.rb
class Capacity < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '8' },
    { id: 3, name: '10' },
    { id: 4, name: '12' },
    { id: 5, name: '14' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :area
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :tide

  validates :weather, presence: true
  validates :wave, presence: true, numericality: true, format: { with: /\A-?[0-9]+(\.[0-9]+)?\z/ }

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :wind
    validates :temperature
    validates :water_temperature
  end
  with_options numericality: { other_than: 1 } do
    validates :tide_id
  end
end

app/models/entry.rb
class Entry < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ボートダイブ' },
    { id: 3, name: 'ビーチダイブ' },
    { id: 4, name: 'ドリフトダイブ' },
    { id: 5, name: 'ナイトダイブ' }
  ]

  include ActiveHash::Associations
  has_many :areas
end

app/models/equipment.rb
class Equipment < ApplicationRecord

  belongs_to :area

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :capacity
  belongs_to :type
  belongs_to :suitstype

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :area, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :capacity
  belongs_to :type
  belongs_to :suitstype

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :thickness
    validates :weight
  end
  with_options numericality: { other_than: 1 } do
    validates :suitstype_id
    validates :capacity_id
    validates :type_id
  end
end

app/models/logbook.rb
class Logbook < ApplicationRecord
  belongs_to :area, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :entry_time
    validates :exit_time
  end
  with_options presence: true do
    validates :text
    validates :point
  end

  with_options presence: true, numericality: true, format: { with: /\A[0-9]+\z/ } do
    validates :start_air
    validates :finish_air
    validates :max_depth
    validates :ave_depth
    validates :count
  end

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/month.rb
class Month < ActiveHash::Base
  self.data = [
    { id: 1, name: '' },
    { id: 2, name: '01' },
    { id: 3, name: '02' },
    { id: 4, name: '03' },
    { id: 5, name: '04' },
    { id: 6, name: '05' },
    { id: 7, name: '06' },
    { id: 8, name: '07' },
    { id: 9, name: '08' },
    { id: 10, name: '09' },
    { id: 11, name: '10' },
    { id: 12, name: '11' },
    { id: 13, name: '12' }
  ]

  include ActiveHash::Associations
  has_many :area
end

app/models/suitstype.rb
class Suitstype < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ウェットスーツ' },
    { id: 3, name: 'ドライスーツ' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/tide.rb
class Tide < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'なし' },
    { id: 3, name: 'とても弱い' },
    { id: 4, name: '弱い' },
    { id: 5, name: '強い' },
    { id: 6, name: 'とても強い' }
  ]

  include ActiveHash::Associations
  has_many :conditions
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :text, presence: true
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'アルミ' },
    { id: 3, name: 'スチール' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :areas, dependent: :destroy
  has_many :tweets
end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [
    { id: 1, name: '' },
    { id: 2, name: '2020' },
    { id: 3, name: '2021' },
    { id: 4, name: '2022' },
    { id: 5, name: '2023' },
    { id: 6, name: '2024' },
    { id: 7, name: '2025' },
    { id: 8, name: '2026' },
    { id: 9, name: '2027' },
    { id: 10, name: '2028' },
    { id: 11, name: '2029' },
    { id: 12, name: '2030' },
    { id: 13, name: '2031' },
    { id: 14, name: '2032' },
    { id: 15, name: '2033' },
    { id: 16, name: '2034' },
    { id: 17, name: '2035' },
    { id: 18, name: '2036' },
    { id: 19, name: '2037' },
    { id: 20, name: '2038' },
    { id: 21, name: '2039' },
    { id: 22, name: '2040' },
    { id: 23, name: '2041' },
    { id: 24, name: '2042' },
    { id: 25, name: '2043' },
    { id: 26, name: '2044' },
    { id: 27, name: '2045' },
    { id: 28, name: '2046' },
    { id: 29, name: '2047' },
    { id: 30, name: '2048' },
    { id: 31, name: '2049' },
    { id: 32, name: '2050' }
  ]

  include ActiveHash::Associations
  has_many :area
end

app/controllers/logbooks_controller.rb
class LogbooksController < ApplicationController
  def index
    @tweets = Tweet.all.order('created_at DESC')
    @today = Date.today.strftime('%Y年%m月%d日')
  end

  def new
    @logbook = Logbook.new
  end

  def create
    logbook = Logbook.new(logbook_params)
    if logbook.save
      redirect_to user_path(current_user.id)
    else
      redirect_to new_area_logbook_path
    end
  end

  def show
  end

  private

  def logbook_params
    params.require(:logbook).permit(:image, :point, :start_air, :finish_air, :max_depth, :ave_depth, :entry_time, :exit_time, :count, :text).merge(area_id: params[:area_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logbooks_helper.rb
module LogbooksHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/logbooks/index.html.erb
<body>
  <%= render "shared/header" %>
  <div class="head-group">
    <% if user_signed_in? %>
    <div class="today">
      <div>こんにちは　<%= link_to current_user.nickname, user_path(current_user.id), class: "top-user-nickname" %>さん</div>
      <div><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"session-text" %></div>
    </div>
    <% else %>
    <div class="today">
      <h5>サービスを利用するにはログイン、またはアカウントの作成してください。</h5>
      <div>
        <%= link_to 'ログイン',  new_user_session_path, class:"session-text" %>
        または
        <%= link_to '新規作成', new_user_registration_path, class:"session-text" %>
      </div>
    </div>
    <% end %>
    <div class="today">
      <%= @today %>
    </div>
  </div>

  <main>
  <div class="top-title">
    <div class="area">
      <div class="main-logo">
        <%= link_to image_tag("toplogo.png", class:"toplogo"), "/" %>
      </div>
      <h1 class="top-main">
        ダイビングのツイートと記録をしよう
      </h1>
    </div>
    <div class="new-edit-btn">
      <% if user_signed_in? %>
        <%= link_to "ツイート投稿", new_tweet_path, class:"head-text" %>
        <%= link_to "ログの入力", new_area_path, class:"head-text" %>
        <%= link_to "マイページ", user_path(current_user.id), class:"head-text" %>
      <% end %>
    </div>
  </div>

  <div class="explanation">
    <div class="tweet-title-top">
      <p>ログブック</p>
    </div>
    <div class="logbook-exp">
      <%= image_tag("pc-image.png", class:"toplogo") %>
      <p>その日のダイビングの情報を写真とともに記録することもできます。</p>
      <% if user_signed_in? %>
      <p>ログブックの入力は<%= link_to "こちら", new_area_path %></p>
      <% end %>
    </div>
  </div>
  <% if @tweets.present? %>
  <p class="tweet-title-top">ツイート一覧</p>
  <ul class="tweet-contents">
    <li class="tweet-list">
      <% @tweets.each do |tweet| %>
      <div class="group">
        <div class="tweet-image-area">
            <%= image_tag tweet.image.variant(resize: '600x400'), class: 'tweet-image' if tweet.image.attached? %>
        </div>
        <div class="tweets-nickname-area">
          <h3 class="tweets-nickname">
            投稿者：<%= tweet.user.nickname %>
            <P>投稿日：<%= l tweet.user.created_at %></p>
          </h3>
          <div class="tweet-text">
            <%= tweet.text %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
    </li>
  </ul>
</main>
<%= render "shared/footer" %>
</body>

app/views/logbooks/new.html.erb
<%= render "shared/second-header" %>

<div class="area">
  <div class="area-left">
  </div>
  <div class="area-center">
  <h2 class="log-title">ログを入力</h2>
  <%= form_with(model: @logbook, url: area_logbooks_path, local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="log-form">
    <div class="left-form">
      <p>point</P>
        <%= f.text_field :point, class:"log-input", id:"point", placeholder:"例）マンタスクランブル", class: "form-field" %>
      <p>Start Air</P>
        <%= f.text_field :start_air, class:"log-input", id:"start_air", placeholder:"例）200", class: "form-field" %>
      <p>Finish Air</P>
        <%= f.text_field :finish_air, class:"log-input", id:"finish_air", placeholder:"例）90", class: "form-field" %>
      <p>Max Depth</P>
        <%= f.text_field :max_depth, class:"log-input", id:"max_depth", placeholder:"例）20", class: "form-field" %>
      <p>Ave Depth</P>
        <%= f.text_field :ave_depth, class:"log-input", id:"min_depth", placeholder:"例）12", class: "form-field" %>
    </div>
    <div class="right-form">
      <p>Entry time</P>
        <%= f.text_field :entry_time, class:"log-input", id:"entry_time", placeholder:"例）13:30", class: "form-field" %>
      <p>Exit time</P>
        <%= f.text_field :exit_time, class:"log-input", id:"exit_time", placeholder:"例）15:00", class: "form-field" %>
      <p>Count</P>
        <%= f.text_field :count, class:"log-input", id:"count", placeholder:"例）1", class: "form-field" %>
      <p>備考</P>
        <%= f.text_area :text, class:"log-input", id:"text", placeholder:"例）発見した生物、バディの名前など", class: "form-field" %>
    </div>
  </div>
    <div class="log-image">
      <p>画像の保存</p>
        <%= f.file_field :image, id:"log-image" %>
    </div>
    <div class="log-submit">
      <%= f.submit "記録する", class:"submit-send-btn" %>
    </div>
  <% end %>
  </div>

  <div class="area-right">
  </div>
</div>